CREATE TABLE IF NOT EXISTS users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"          VARCHAR(100),
    email           VARCHAR(100) UNIQUE,
    phone_number    VARCHAR(16),
    address         TEXT,
    created_at      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by      BIGINT,
    updated_at      TIMESTAMPTZ,
    updated_by      BIGINT,
    deletad_at      TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS products (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"          VARCHAR(100),
    description     TEXT,
    created_at      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by      BIGINT,
    updated_at      TIMESTAMPTZ,
    updated_by      BIGINT,
    deletad_at      TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS product_variants (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id      BIGINT REFERENCES products(id),
    price           NUMERIC(12,2) NOT NULL,
    stock           INT NOT NULL DEFAULT 0,
    weight          INT NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by      BIGINT,
    updated_at      TIMESTAMPTZ,
    updated_by      BIGINT,
    deletad_at      TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS product_options (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id              BIGINT REFERENCES products(id),
    "name"                  VARCHAR(50),
    created_at              TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by              BIGINT,
    updated_at              TIMESTAMPTZ,
    updated_by              BIGINT,
    deletad_at              TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS product_option_values (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_option_id       BIGINT REFERENCES products(id),
    "value"                 VARCHAR(50),
    created_at              TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by              BIGINT,
    updated_at              TIMESTAMPTZ,
    updated_by              BIGINT,
    deletad_at              TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS product_variant_option_values (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_variant_id      BIGINT REFERENCES product_variants(id),
    product_option_value_id BIGINT REFERENCES product_option_values(id),
    created_at              TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by              BIGINT,
    updated_at              TIMESTAMPTZ,
    updated_by              BIGINT,
    deletad_at              TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS carts (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                 BIGINT REFERENCES users(id),
    created_at              TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by              BIGINT,
    updated_at              TIMESTAMPTZ,
    updated_by              BIGINT,
    deletad_at              TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS cart_items (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id                 BIGINT REFERENCES carts(id),
    product_variant_id      BIGINT REFERENCES product_variants(id),
    qty                     INT NOT NULL DEFAULT 0,
    created_at              TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by              BIGINT,
    updated_at              TIMESTAMPTZ,
    updated_by              BIGINT,
    deletad_at              TIMESTAMPTZ
);

CREATE TYPE order_status AS ENUM (
    'PENDING',
    'PAID',
    'SHIPPED',
    'COMPLETED',
    'CANCELED'
);

CREATE TABLE IF NOT EXISTS orders (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                 BIGINT REFERENCES users(id),
    status                  order_status NOT NULL DEFAULT 'PENDING',
    ordered_at              TIMESTAMPTZ,
    total                   NUMERIC(12,2) NOT NULL DEFAULT 0,
    city_id                 BIGINT,
    city_name               VARCHAR(100),
    address                 TEXT,
    courier                 VARCHAR(20),
    courier_service         VARCHAR(20),
    shipping_cost           NUMERIC(12,2) NOT NULL DEFAULT 0,
    grand_total             NUMERIC(12,2) NOT NULL DEFAULT 0,
    created_at              TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by              BIGINT,
    updated_at              TIMESTAMPTZ,
    updated_by              BIGINT,
    deletad_at              TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS order_items (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id                BIGINT REFERENCES orders(id),
    product_variant_id      BIGINT REFERENCES product_variants(id),
    price                   NUMERIC(12, 2) NOT NULL DEFAULT 0,
    qty                     INT NOT NULL DEFAULT 0,
    subtotal                NUMERIC(12, 2) NOT NULL DEFAULT 0,
    created_at              TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by              BIGINT,
    updated_at              TIMESTAMPTZ,
    updated_by              BIGINT,
    deletad_at              TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS districts (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    district                VARCHAR(100),
    district_id             BIGINT,
    created_at              TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by              BIGINT,
    updated_at              TIMESTAMPTZ,
    updated_by              BIGINT,
    deletad_at              TIMESTAMPTZ
);