ALTER TABLE orders
    DROP COLUMN IF EXISTS payment_type,
    DROP COLUMN IF EXISTS midtrans_transaction_id,
    DROP COLUMN IF EXISTS payment_status;

CREATE TABLE IF NOT EXISTS order_payments (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id                BIGINT REFERENCES orders(id),
    payment_type            VARCHAR(30),
    midtrans_transaction_id VARCHAR(50),
    va_number               VARCHAR(50),
    qris_url                TEXT,
    payment_status          payment_status DEFAULT 'PENDING',
    paid_at                 TIMESTAMPTZ,
    expired_at              TIMESTAMPTZ,
    created_at              TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by              BIGINT,
    updated_at              TIMESTAMPTZ,
    updated_by              BIGINT,
    deleted_at              TIMESTAMPTZ
);