CREATE TABLE IF NOT EXISTS sub_districts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sub_district    VARCHAR(100),
    sub_district_id BIGINT,
    district_id     BIGINT,
    created_at      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by      BIGINT,
    updated_at      TIMESTAMPTZ,
    updated_by      BIGINT,
    deleted_at      TIMESTAMPTZ
);

INSERT INTO sub_districts
    (sub_district, sub_district_id, district_id, created_at)
VALUES
    ('CICADAS', 4904, (SELECT id FROM districts WHERE district = 'Bandung'), CURRENT_TIMESTAMP),
    ('MEDANG', 73581, (SELECT id FROM districts WHERE district = 'Tangerang'), CURRENT_TIMESTAMP);